### ISSUE TITLE
Uncaught Reference Error

### ISSUE THREAD

**Issue by shimastripe** [msiniscalchi/atom-latextools#1]
![false](https://cloud.githubusercontent.com/assets/15936908/12187639/dffeee0e-b5f0-11e5-9ed3-867adb91d7ee.png)

Uncaught Reference Error has occured. Please check the /latextools/lib/parseTexlog.coffee:200.
<img width="845" alt="2016-01-08 10 18 22" src="https://cloud.githubusercontent.com/assets/15936908/12187799/555b6212-b5f2-11e5-8704-8696a5e5117a.png">

At 200 line, you should modify "False" to "false".

**Comment by msiniscalchi** [comment]
Great catch! Just pushed a fix to master. Thank you @shimastripe !
