### ISSUE TITLE
Uncaught TypeError: Cannot read property 'split' of null

### ISSUE THREAD

**Issue by doblak** [msiniscalchi/atom-latextools#104]
Using new environment with \input{bk10.clo} breaks citation popup. Thanks for investigating (or at least giving some directions)

[Enter steps to reproduce below:]

1. Add localsize environment: http://tex.stackexchange.com/questions/4139/how-to-change-font-size-mid-document/87908#87908
2. even using directly bk10.clo instead of argumented bk#1.clo, using \cite{ fails - when the popup should appear, an error is thrown:Could not find bk10.clo

**Atom Version**: 1.7.4
**System**: Linux Mint
**Thrown From**: [latextools](https://github.com/msiniscalchi/atom-latextools) package, v0.8.1

### Stack Trace

Uncaught TypeError: Cannot read property 'split' of null

```
At /home/oblak/.atom/packages/latextools/lib/completion-manager.coffee:198

TypeError: Cannot read property 'split' of null
    at CompletionManager.module.exports.CompletionManager.CompletionManager.citeComplete (/home/oblak/.atom/packages/latextools/lib/completion-manager.coffee:198:27)
    at CompletionManager.module.exports.CompletionManager.CompletionManager.refCiteComplete (/home/oblak/.atom/packages/latextools/lib/completion-manager.coffee:132:8)
    at /home/oblak/.atom/packages/latextools/lib/latextools.coffee:234:28
```

### Commands

```
  7x -0:03.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:01.0 latextools:ref-cite-keypress (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "latexer",
      "latex"
    ]
  },
  "latextools": {
    "builderSettings": {},
    "darwin": {},
    "linux": {},
    "win32": {}
  }
}
```

### Installed Packages

```coffee
# User
git-diff-details, v0.23.0
language-latex, v0.6.1
language-matlab, v0.2.1
language-r, v0.4.1
latextools, v0.8.1
linter, v1.11.4
linter-chktex, v1.3.0
markdown-preview-plus, v2.4.0

# Dev
No dev packages
```

**Comment by PaulEcoffet** [comment]
I have the same issue with tikz imports.
```latex
\input{F.tikz}
```

makes the cite pop up crash with the same error.
