### ISSUE TITLE
does not launch pdf-view or skim

### ISSUE THREAD

**Issue by mkleban** [msiniscalchi/atom-latextools#106]
With either "pdf-view" or "default" selected in the "viewer" preference, latextools correctly compiles latex files (it creates pdf files that look fine when I open them from the finder), but it fails to launch a pdf viewer in atom.  I have skim installed.   Macbook air 2013, OSX 10.11.2 (El Capitan).

More details: I compile a latex file and see a notification that the build completed with 0 errors and 0 warnings.  The console says "jumping to PDF", but nothing happens.

Here's the console output:

Platform: darwin; texpath: /Library/TeX/texbin:/usr/texbin:/usr/local/bin:/opt/local/bin
Setting PATH = /sw/bin:/sw/sbin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/texbin:/usr/local/bin:/Library/TeX/texbin:/usr/texbin:/usr/local/bin:/opt/local/bin:/Library/TeX/texbin:/usr/texbin:/usr/local/bin:/opt/local/bin:/Library/TeX/texbin:/usr/texbin:/usr/local/bin:/opt/local/bin:/Library/TeX/texbin:/usr/texbin:/usr/local/bin:/opt/local/bin:/Library/TeX/texbin:/usr/texbin:/usr/local/bin:/opt/local/bin:/Library/TeX/texbin:/usr/texbin:/usr/local/bin:/opt/local/bin:/Library/TeX/texbin:/usr/texbin:/usr/local/bin:/opt/local/bin:/Library/TeX/texbin:/usr/texbin:/usr/local/bin:/opt/local/bin:/Library/TeX/texbin:/usr/texbin:/usr/local/bin:/opt/local/bin:/Library/TeX/texbin:/usr/texbin:/usr/local/bin:/opt/local/bin:/Library/TeX/texbin:/usr/texbin:/usr/local/bin:/opt/local/bin:/Library/TeX/texbin:/usr/texbin:/usr/local/bin:/opt/local/bin
Processing file test (test) in directory /Users/XXX/
latexmk builder
latexmk -cd -e -f -pdf -interaction=nonstopmode -synctex=1 "test"
Parsing /Users/XXX/test.log
ERRORS:
WARNINGS:
Jumping to PDF...

**Comment by ig0774** [comment]
It sounds like its not actually hitting the viewer code at all. Could you try uninstalling and reinstalling the plugin?

**Comment by mkleban** [comment]
I just tried, and got the following error: 

"Uninstalling “latextools” failed.  Failed to delete latextools: Does not exist"

I uninstalled atom and deleted the directory ~/.atom, reinstalled atom from a new download, installed the latextools package, and then tried again to uninstall it.  Same error as above.

**Comment by ig0774** [comment]
That sounds like it might be atom/atom#11464, which I gather from that issue, is just a harmless error that will be fixed when Atom 1.9 is released.

The real question is does the issue persist after reinstalling the plugin?

**Comment by mkleban** [comment]
The issue persists just as before (sorry for not making that clear).

**Comment by ig0774** [comment]
I just re-looked through your log: is you file, in fact, just named `test` and not `test.tex`? If so, could you rename it to `test.tex` and try to compile it? The view command checks the file extension to see if it's a known `tex` file extension.

**Comment by mkleban** [comment]
That made a big difference - good catch!  However I'm not sure things are working quite correctly.  If I select "pdf-view" in the latextools preferences, compiling now produces a new pane labeled test.pdf.

If I select "default", skim launches and the pdf displays correctly, but in its own window that appears behind the atom window and last in the alt-tab list of open applications (not in a pane).  Is that supposed to happen?

Thanks very much for your help, by the way.

**Comment by ig0774** [comment]
`pdf-view` requires the [pdf-view](https://atom.io/packages/pdf-view) package, which needs to be installed separately. Otherwise, it just ends up telling Atom to open the document, which isn't very useful.

Regarding Skim, by default, latextools is setup to keep the focus on Atom which means that Skim is opened in the background, hence the behaviour you're seeing. If you uncheck the "Keep Focus" setting (in the latextools settings), Skim will launch and gain the focus.

We don't have the ability to control where Skim opens and I'm not entirely certain how OS X determines the position, but I think it remembers the last position used. Personally, I use[ShiftIt](https://github.com/fikovnik/ShiftIt) to keep Atom open on one side of my screen and Skim on the other.
