### ISSUE TITLE
Auto triggering for cite and ref does not work

### ISSUE THREAD

**Issue by PierreMarchand20** [msiniscalchi/atom-latextools#115]
I can use the keybinding cmd-l x (I am on OSX) to show references and citations but auto triggering does not work. It is supposed to be activated according to the settings but it does not work.

**Comment by JorgeGT** [comment]
I'm guessing you have a French keyboard layout, Pierre? I have the same problem with the Spanish layout, it seems that Atom has problems with keybindings in non-US keyboard layouts. If I switch my layout to EN_US auto triggering works, with ES_ES it does not.

**Comment by ig0774** [comment]
Also see #98. I've had mixed results with the [keyboard-localization](https://github.com/andischerer/atom-keyboard-localization) plugin. It works really well for some layouts and sometimes yields bizarre results for others.

**Comment by PierreMarchand20** [comment]
Well, I am unmasked ! I guess my name sounds very french... Thank you for your answers, it actually works when I use an american layout but it does not with the french layout, even with the keyboard-localization plugin. It is unfortunate since it is pretty hard to use an american layout with a french keyboard.

But I do not understand why it only affects auto triggering, since we precisely do not use the keyboard in that case while when we use the keybinding, it works.

**Comment by JorgeGT** [comment]
I can confirm that the keyboard-localization plugin doesn't solve this issue for me with the ES_ES layout.

**Comment by ig0774** [comment]
Actually, the auto-triggering uses a keybinding as well, which was intended to solve a couple of other issues (see #90). Unfortunately, I don't have a good solution that addresses both the problems with the old implementation (which doesnt suffer from the keybinding issue) and doesn't suffer from the key binding issue.

**Comment by PierreMarchand20** [comment]
One can hope that they will fix the keymap issue in Atom one day. I think we can stick with the usual keybinding for now.

**Comment by JorgeGT** [comment]
@PierreMarchand20 The latest Atom beta solves this issue for me, if you are interested in testing it.

**Comment by PierreMarchand20** [comment]
It seems to work well with Atom beta ! They did quite a job (http://blog.atom.io/2016/10/17/the-wonderful-world-of-keyboards.html)
