### ISSUE TITLE
Reflow should respect environments

### ISSUE THREAD

**Issue by cortner** [msiniscalchi/atom-latextools#116]
When I reflow a paragraph which borders environment boundaries (`begin`, `end`) then it will reflow also these environments. See the following images:

**Before reflow:**
<img width="639" alt="notaligned" src="https://cloud.githubusercontent.com/assets/7688515/17496061/81f32e90-5db3-11e6-9b99-93844cedbdfd.png">

**After reflow:** (text not highlighted)
<img width="658" alt="badalign" src="https://cloud.githubusercontent.com/assets/7688515/17496075/9141b1fa-5db3-11e6-9e06-77034d34dbec.png">

I wonder whether the reflow command can somehow be taught to respect latex environments? Maybe there is a way to tell Atom what a paragraph is?

**Comment by ig0774** [comment]
This has already been reported to the atom-autoflow plugin as an issue (see atom/autoflow#18), which is probably the best place to go to get this fixed. Unfortunately, I can't see any *obvious* way we can plug into either the autoflow plugin or the definition of a "paragraph" that's determined by the (undocumented) `LanguageMode` class. Atom's notion of a "paragraph" makes sense for Markdown and programming languages, but doesn't work very well for LaTeX.

In the meantime, if you add a blank line after `\begin{}` and before `\end{}` autoflow will do the right thing. So something like:

```latex
\begin{theorem}

       Lorem ipsum dolor sit amet, consectetur adipiscing 
       elit. Morbi et nisi viverra, sollicitudin ante sit amet, iaculis purus. Donec suscipit
 nisl ac sem porttitor, non tempus tortor feugiat. Suspendisse eget lorem mattis, ultricies quam id, auctor dolor. Curabitur dignissim at sem eget eleifend. Maecenas eleifend diam est, sit amet tristique elit 
condimentum sit amet. Nulla ac euismod odio. Sed quis commodo eros. Phasellus gravida orci quis leo finibus consequat. Aliquam et mi sit amet tellus dignissim gravida ut sed ex. Suspendisse volutpat 
          feugiat ultrices. Integer volutpat, augue in eleifend elementum, felis diam fermentum lacus, a venenatis orci sem et eros. Integer viverra diam eget ex ullamcorper dignissim sed eu eros.

\end{theorem}
```

**Comment by cortner** [comment]
Some environments won't allow that. One can then still add comments
```
\begin{theorem}
%
       Lorem ipsum dolor sit amet, consectetur adipiscing 
       elit. Morbi et nisi viverra, sollicitudin ante sit amet, iaculis purus. Donec suscipit
 nisl ac sem porttitor, non tempus tortor feugiat. Suspendisse eget lorem mattis, ultricies quam id, auctor dolor. Curabitur dignissim at sem eget eleifend. Maecenas eleifend diam est, sit amet tristique elit 
condimentum sit amet. Nulla ac euismod odio. Sed quis commodo eros. Phasellus gravida orci quis leo finibus consequat. Aliquam et mi sit amet tellus dignissim gravida ut sed ex. Suspendisse volutpat 
          feugiat ultrices. Integer volutpat, augue in eleifend elementum, felis diam fermentum lacus, a venenatis orci sem et eros. Integer viverra diam eget ex ullamcorper dignissim sed eu eros.
%
\end{theorem}
```

But this is really a poor fix that especially doesn't work when you collaborate.

**Comment by ig0774** [comment]
I understand that its not a great solution; unfortunately, its the only thing that can be done without monkey patching either Atom or autoflow, either of which would be extremely fragile.

**Comment by cortner** [comment]
I fully understand this is not fixable from within latex tools. sorry this wasn't clear from my reply. feel free to close if it is considered somewhere else anyhow. 

Any chance the main Atom project will actually fix this?
