### ISSUE TITLE
Broken Russian layout

### ISSUE THREAD

**Issue by JackGin** [msiniscalchi/atom-latextools#119]
Hi,

it looks like installing latextools breaks Russian keyboard layout. Instead of э and ё one gets `'. With latextools disabled, the layout is ok. Installing the keyboard localization package solves this problem, but breaks the shortcuts instead (like, the compile shortcut). Is there a way to remedy things? Atom v.1.9 for Linux.
Thank you!

**Comment by ig0774** [comment]
You could always add this to your `keymap` file:

```
"atom-text-editor[data-grammar~='latex']":
  '`' : 'unset!'
  '\'': 'unset!'
```

Which should remove the bindings in question. Alternatively, you could re-bind whatever shows up in the "Key Binding Resolver" when you press `ctrl-alt-b` to the `'latextools:build'` command and work with the keyboard localization package.

I realise neither of those options are ideal, but it's the best we can do to work around what is fundamentally an issue in Atom itself.

**Comment by JackGin** [comment]
Dear ig0774, thank you so much. Keymap modification works. And I was so reluctant to switch back to Sublime...:)
