### ISSUE TITLE
latextools:build keybinding fails

### ISSUE THREAD

**Issue by lsfinn** [msiniscalchi/atom-latextools#121]
Platform: Mac OSX 10.11.6
Atom v1.9.9
latextools v0.8.2
Other installed packages: 
  git-plus v5.16.2
  grammar-token-limit 0.1.1
  language-latex 0.6.1
  linter 1.11.16
  linter-check 1.3.0

When I attempt to build a latex file using the keybinding (cmd-alt-b) I get a system beep error and nothing happens. When I attempt to build by going to the command palette and invoking latextools:build directly everything behaves as it should: i.e., the file builds, the LatexTools console opens, skim opens with the PDF and the focus shifts to skim.

**Comment by ig0774** [comment]
I can't reproduce this with a similar setup. Can you turn on the *Key Binding Resolver* (`cmd-.`) and look at what bindings its shows when you press `cmd-alt-b` in a LaTeX document?

Also, is the *syntax* for the file set to `LaTeX` like this:

<img width="142" alt="screen shot showing synxtax set to LaTeX" src="https://cloud.githubusercontent.com/assets/212893/18001997/701f0018-6b7d-11e6-8da4-a5cebde9af9d.png">

If not, none of the latextools keybindings will work.

**Comment by lsfinn** [comment]
Hi - With the particular key combination cmd-alt-b the system gives its error beep and nothing shows in the resolver. Other keys or key  combinations do show in the resolver.

Thoughts?

Thanks,

Sam

--
Lee Samuel Finn
Professor, Dept Physics;
  Dept Astronomy & Astrophysics
The Pennsylvania State University
104 Davey Laboratory
University Park, PA 16802

**Comment by lsfinn** [comment]
Found the problem: there is another app that I always have running (Vitamin-R) that also binds to cmd-alt-b. Changing the binding frees atom to capture the shortcut.

This problem report can be resolved.

Thanks much,

Sam

--
Lee Samuel Finn
Professor, Dept Physics;
  Dept Astronomy & Astrophysics
The Pennsylvania State University
104 Davey Laboratory
University Park, PA 16802

**Comment by ig0774** [comment]
Ah that makes sense! Glad you managed to get thing ms working!
