### ISSUE TITLE
How to room the generated pdf file?

### ISSUE THREAD

**Issue by Edenharder** [msiniscalchi/atom-latextools#130]
Even I put the cursor in the pdf file, the `cmd +` or `cmd -` will only affect the original tex file.

**Comment by r-stein** [comment]
Do you want to zoom into the pdf?

**Comment by Edenharder** [comment]
@r-stein yes, zoom the pdf file.

**Comment by r-stein** [comment]
This is a feature of your pdf viewer, you should focus the viewer first and then it depends. For Skim see [Skim Help](http://skim-app.sourceforge.net/manual/SkimHelp_2.html). For the atom integrated viewer the named keybindings should work, but you need to focus the tab.

**Comment by Edenharder** [comment]
@r-stein Thanks, it works. I should focus on the tab firstly, focus on the file but not the tab does not work.
