### ISSUE TITLE
Default viewer using atom on macOS not working

### ISSUE THREAD

**Issue by hpfister** [msiniscalchi/atom-latextools#131]
I am using atom 1.10.2 on macOS Sierra 10.12 with latextools 0.8.2. When I am compiling a Latex file with the "default" viewer option enabled I get the following error:

Executing /Users/hpfister/.atom/packages/latextools/lib/displayfile -r -g '".../NSFmaster.pdf"'
ERROR ENOENT

Turns out that /Users/hpfister/.atom/packages/latextools/lib/displayfile does not exist when I search for it in terminal.

Am I missing anything? E.g., a PATH setting? 

Thank you,

- HP

**Comment by ig0774** [comment]
You're not missing anything. It's a bug / typo. I'll try to get a fix together shortly.

**Comment by ig0774** [comment]
Thanks for the bug report. This has been fixed in v0.8.3.

**Comment by hpfister** [comment]
Thank you - but it created a new error. I created a bug report with the stack trace. 

- HP
