### ISSUE TITLE
Citation autocompletion

### ISSUE THREAD

**Issue by HamletGhost** [msiniscalchi/atom-latextools#14]
Citation autocompletion does not work for me, maybe because I am not using the compilation interface of this package. When I type \cite{}, a search window (text input box) appears with no options. So far, no bug.
I hit <ESC> and go on typing, and almost at every letter (depending on how fast I type), that same window steals focus again and again. Any text I type in that window is lost.
Suggested fixes:
* workaround: implement the option to disable the autocompletion (seems not to have any effect now; no surprise, given the warning in the package description)
* trigger the autocompletion only once (reset it when the cursor exits the \cite{} scope)
* copy the text typed in the window into the \cite{} verbatim when it does not match anything

**Comment by pbrueske** [comment]
Same goes for me. I am building my document with a Grunt job and use Atom just for editing.
Atom: 1.3.2
Distribution: Ubuntu 14.04

**Comment by msiniscalchi** [comment]
Hi @HamletGhost and @pbrueske .

Hmm... looks like bib files are not found, so completion fails (silently).  First of all, to clarify:

- Completion only works with bibliographies in bib files, not for references provided using the `\bibitem` command.
- bib files must be indicated using the usual `\bibliography` (or `\addbibresource`) command, specifying the path relative to the tex file (the master tex file, in a multi-file document). So for instance bib files in your `texmf` tree are not yet supported on Atom (they are on Sublime Text). 

Anyway, I have just pushed a couple of commits to master. Ref / cite toggles (Settings) are now honored. Also, if a bib file is not found, the user is informed. These are in master, but not yet in a tagged release. I hope to be able to do a release later today.

In the meantime, can you check your tex file and/or the console to see if bib files are correctly identified? I'm assuming they are not.

**Comment by pbrueske** [comment]
@msiniscalchi thanks, adding the .bib file via \addbibresource works for me. :+1:

**Comment by msiniscalchi** [comment]
If all is OK (or at least better) now, can I close?

BTW @pbrueske on a different topic, would the ability to integrate your Grunt job with LaTeXTools be useful to you? What I mean is this: when you hit Ctrl-Alt-B, your grunt job runs, then LaTeXTools picks up the log file and displays the errors. The Sublime Text version of the plugin does have this feature (you can redefine the build command), and I was planning to add it to Atom, too.

**Comment by pbrueske** [comment]
@msiniscalchi For me its OK to close.

The feature you are describing sounds interesting, but for my current workflow unnecessary. Thanks, anyway ;)
