### ISSUE TITLE
How can I compile .bib files?

### ISSUE THREAD

**Issue by xzhang-wr** [msiniscalchi/atom-latextools#149]
Hi,

This might be a stupid question. I have some references in my document I've written in the .bib file. Do I need to do something else other than Ctrl+Alt+B to compile it so that I can have it in the pdf it produces?

Currently, I do the build command the references won't show up in the PDF.

Thank you!

**Comment by r-stein** [comment]
You need to add something like

``` latex
\bibliographystyle{abbrv}
\bibliography{mybibliography}
```
at the end of the document, where `mybibliography.bib` is your bibliography file.

**Comment by xzhang-wr** [comment]
Thank you! 

Never mind, I found the problem. 

The template I'm using rrquires a very weird formation for .bib. I didn't know this so it didn't like my .bib so never compiled. It is working now.

Thank you!
