### ISSUE TITLE
Arch/Manjaro Linux: Issues with xelatex

### ISSUE THREAD

**Issue by tifrel** [msiniscalchi/atom-latextools#170]
The shortcut for building a latex file on Manjaro (a distro built upon Arch) seems to be somewhat broken. Console output:

    Latexmk: Changing directory to '/home/test/'
    Latexmk: Run number 1 of rule 'pdflatex'
    This is pdfTeX, Version 3.14159265-2.6-1.40.18 (TeX Live 2017/Arch Linux) (preloaded format=pdflatex)
     \write18 enabled.
    entering extended mode
    Latexmk: Log file says no output from latex
    Latexmk: For rule 'pdflatex', no output was made
    Collected error summary (may duplicate other messages):
      pdflatex: Command for 'pdflatex' gave return code 1
          Refer to 'test.log' for details
    Latexmk: Undoing directory change
    Latexmk: Use the -f option to force complete processing, unless error was exceeding maximum runs of latex/pdflatex.
    [Finished in 0.438s]

Log file contains the following:

    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    !
    ! Fatal fontspec error: "cannot-use-pdftex"
    ! 
    ! The fontspec package requires either XeTeX or LuaTeX.
    ! 
    ! You must change your typesetting engine to, e.g., "xelatex" or
    ! "lualatex"instead of plain "latex" or "pdflatex".
    ! 
    ! See the fontspec documentation for further information.
    ! 
    ! For immediate help type H <return>.
    !...............................................  
                                                  
    l.28 \msg_fatal:nn {fontspec} {cannot-use-pdftex}

`xelatex` is selected as Builder Settings Program, and manually inserting the `-pdfxe`, `-xelatex` `-f` flags to the Builder Settings Options line did not help. Neither did any combination thereof. Running `latexmk -xelatex` works just fine, so does `latexmk -pdfxe`. Running pdflatex without fontenc (and without xetex) is fine and produces the following console output:

    Latexmk: Changing directory to '/home/test/'
    Latexmk: Run number 1 of rule 'pdflatex'
    This is pdfTeX, Version 3.14159265-2.6-1.40.18 (TeX Live 2017/Arch Linux) (preloaded format=pdflatex)
     \write18 enabled.
    entering extended mode
    For rule 'view', running '&if_source(  )' ...
    Latexmk: Undoing directory change
    sh: acroread: command not found
    [Finished in 0.496s]

Nothing quirky in the .log file either. I have basically the same Atom + latextools setup running on macOS without issues. Both systems run TeX-live, which on linux is installed to /usr/bin/ (because pacman did it like that). Also pointing latextools to the appropriate paths and builders manually didn't change anything on console output or logfile.

Thanks for reading,
Till

Edit: Reinstalling LaTeX didn't fix it either

**Comment by ig0774** [comment]
Are you certain you're invoking LaTeXTools and not some other bit? Basically, LaTeXTools should never output the console output you're reporting, so I can't think where that's coming from.

Do you have any other latex-related plugins installed?

**Comment by tifrel** [comment]
I didn't have any other plugins installed that would interfere. However looking at the keybindings, its `ctrl-alt-b` to run latextools, not `ctrl-shift-b`, which invokes the script package. Excuse my stupidious self.
