### ISSUE TITLE
Inverse search fails in Okular

### ISSUE THREAD

**Issue by edwinksl** [msiniscalchi/atom-latextools#25]
Inverse search seems to fail in Okular (I have assumed that Ctrl + click inside Okular is the keybind for doing inverse search.). Forward search works fine though. This is in Atom 1.5.0-beta0 in Ubuntu 15.10.

**Comment by msiniscalchi** [comment]
Sorry for asking, but did you configure Okular to invoke atom? Inverse search is really mainly driven by the PDF viewer; all LaTeXTools does is pass the `--synctex=1` option to the tex engine when compiling. (Forward search OTOH is LaTeXTools' responsibility.)

I have tested this with atom-1.4.0 on Ubuntu 15.10. If there are issues with atom-1.5.0-beta0, that's bad news...

**Comment by edwinksl** [comment]
I tried configuring it but I am pretty sure I messed it up. What is the correct way of configuring Okular?

**Comment by msiniscalchi** [comment]
Will do---I don't have a linux box or VM near me, but I can check tonight.

**Comment by edwinksl** [comment]
Cool, thanks!

**Comment by msiniscalchi** [comment]
OK, so open Okular, go to Settings | Configure Okular..., select Editor (last option in the column on the left). Then, from the drop-down menu choose Custom Text Editor, and enter

  atom %f:%l

as the command.

**Comment by msiniscalchi** [comment]
Also, it's Shift-Click to inverse-search, not Ctrl-Click.

**Comment by msiniscalchi** [comment]
@edwinksl did this work? If so, please close.

**Comment by edwinksl** [comment]
@msiniscalchi My apologies, I will try it out later today and will close this issue after that. :smile:

**Comment by edwinksl** [comment]
Cool, it works now!

I realized I had to click on "Browse" to make the inverse search work; for some reason, Okular defaults to "Selection".

**Comment by edwinksl** [comment]
Also another quick note that is useful to add in MANUAL.md is to use `atom-beta %f:%l` instead if one is using the beta release of Atom.
