### ISSUE TITLE
Increase size of LaTeXTools console panel

### ISSUE THREAD

**Issue by edwinksl** [msiniscalchi/atom-latextools#30]
Is there a way to increase the size of the LaTeXTools console panel? The information in the console, especially the list of errors and warnings, is extremely useful but I can see only 3 lines at at a time. Seeing more lines would be very helpful.

**Comment by msiniscalchi** [comment]
I am thinking about making it configurable. On Sublime Text, one can simply resize the output panel. I need to investigate how to do so in Atom. (BTW, sorry for stating the obvious, but the panel _is_ at least scrollable.)

**Comment by edwinksl** [comment]
@msiniscalchi It would be nice to have it configurable. Yeah, I did know the panel is scrollable but my list of warnings and errors is pretty long, so scrolling through the list is still quite a pain when there are only 3 lines visible in the panel. Thanks for considering adding this as a feature!

**Comment by gkvallis** [comment]
Could the console also be in color? Red for errors, blue for warmings, black for regular messages etc?

**Comment by msiniscalchi** [comment]
Oh, that is actually planned. It's fairly easy to do; I just haven't gotten around to implementing it.

**Comment by gkvallis** [comment]
Great. More generally, are you looking for comments and suggestions, or just issues and bugs? I realize you must already have your own to-do list, so don't want to add to it unnecessarily.

**Comment by msiniscalchi** [comment]
Very happy to hear comments and suggestions! Sadly, after the winter-break hiatus, work has now hit me  like a tornado, and time is now at a premium---so expect a slowdown in the commits and new versions...

**Comment by gkvallis** [comment]
Yes, term has started here (Exeter, UK), alas! I’ll send you a short compilation of thoughts in a few days, though.

Geoff

On Feb 3, 2016, at 9:52 PM, msiniscalchi <notifications@github.com<mailto:notifications@github.com>> wrote:


Very happy to hear comments and suggestions! Sadly, after the winter-break hiatus, work has now hit me like a tornado, and time is now at a premium---so expect a slowdown in the commits and new versions...
