### ISSUE TITLE
.bib stored in external folder does not read

### ISSUE THREAD

**Issue by chbuschmann** [msiniscalchi/atom-latextools#40]
Biblatex?: 
example of external .bib storage:
`\addbibresource{/Users/cbuschmann/Dropbox/Akademia/Bibliotek/Bibliotek.bib} `
leads to:
`Could not find bib files. Please check your \bibliography statements.`

Only when moving the .bib to the root does latextools find it.

**Comment by ig0774** [comment]
No... Absolute paths. This was already fixed in #34, and will be available in the next release.
