### ISSUE TITLE
ERROR ENOENT when opening pdf with SumatraPDF on Windows

### ISSUE THREAD

**Issue by elmewo** [msiniscalchi/atom-latextools#55]
I get this error after building the PDF (correctly):

```
Executing SumatraPDF.exe -reuse-instance -forward-search F:\\Seafile\\Arbeit\\Papers\\TouchlessInteractionPaper\\touchlessgesturecontrol.tex 128 F:\\Seafile\\Arbeit\\Papers\\TouchlessInteractionPaper\\touchlessgesturecontrol.pdf
ERROR ENOENT

```
Seems to be an issue with the filepath notation with \\\ in Windows. 
It worked for me until 0.7.7.

**Comment by ig0774** [comment]
Actually the double-slashes are a harmless artefact of how that string is generated. The ENOENT error indicates a PATH issue possibly similar to #54 (cmd.exe may properly preprocess quotes in the PATH, which are unnecessary; for completely reasons of cross-platform compatibility, v0.8.0 doesn't use cmd.exe anymore, so if you have a PATH entry like "C:\Program Files (x86)\SumatraPDF", just remove the quotes).

**Comment by elmewo** [comment]
Thank you, that did the trick.
