### ISSUE TITLE
Option of using other PDF readers.

### ISSUE THREAD

**Issue by bearbin** [msiniscalchi/atom-latextools#8]
On Linux, would it be possible to use xdg-open instead of calling a PDF reader directly? It would allow users to choose what PDF reader they want to use. Or is there a particular feature that requires okular?

**Comment by msiniscalchi** [comment]
That kind of customization will come in a later version. However, a key functionality of the okular viewer is inverse/forward search, which you can't get via xdg-open. Evince does support it, though the need for dbus makes things a bit more complex. 

My main objective right now is to see whether Atom is a viable replacement for Sublime Text for LaTeX purposes. It (= Atom, not this plugin per se) is definitely slower at this time, but hopefully things will improve going forward.

Keep the feedback coming!

**Comment by gkvallis** [comment]
Yes, FWIW Atom is definitely viable as a Sublime (or TextMate) replacement for LaTeX, at least IMHO. It is a little slower but not problematically slower, and has a number of other advantages in terms of ease of configurability. 

There are one or two odd problems - like doing a sync from Skim occasionally opens a new Atom editor (on OS X) that then crashes, But please keep going with LaTeXtools development.

**Comment by schlichtanders** [comment]
Hi,

from a user perspective, it might be favourable to use intern pdf viewer like https://atom.io/packages/pdf-view

Is this possible already? It at least says it supports synctex

**Comment by ig0774** [comment]
@schlichtanders: atom-pdf-view supports backward sync (i.e., going from the viewer to an editor) but not forward sync (i.e., going from the editor to the viewer). There's an issue tracking this here izuzak/atom-pdf-view#107 and a PR to add (some of) the required behaviour here izuzak/atom-pdf-view#111.

In any case, some sort of integration will likely be available at a later date when atom-pdf-view has a stable way to support forward sync.

**Comment by schlichtanders** [comment]
thanks for the fast response,
so I probably will wait for a year and come back again ;-)

**Comment by nsaje** [comment]
It should be in less than a year I think :-)

**Comment by ig0774** [comment]
#50 will at least address the narrow goal of making atom-pdf-view usable with latextools, so much less than a year...

**Comment by msiniscalchi** [comment]
pdf-view is in master!
